### ISSUE TITLE
Change homepage and create video tutorial

### ISSUE THREAD

**Issue by miltonchandradas** [atl-itworkshop/docs#39]
Change the look and feel of the home page
Create video tutorial of the entire GitHub process

**Comment by rupakg** [comment]
Merged the first portion of work. Moving the second part to a new story.

**Comment by rupakg** [comment]
![image](https://user-images.githubusercontent.com/8188/63205894-50c25680-c079-11e9-9d78-dc8ddb5ea778.png)
